In [1]:
import numpy as np
from numpy import linalg as la

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
la.det(a)

-9.51619735392994e-16

In [11]:
b = np.array([[1,3],[2,4]])
b

array([[1, 3],
       [2, 4]])

In [12]:
la.inv(b)

array([[-2. ,  1.5],
       [ 1. , -0.5]])

In [13]:
X = np.array([[150,5,1],[100,5,1],[120,10,1]])
X

array([[150,   5,   1],
       [100,   5,   1],
       [120,  10,   1]])

In [14]:
y = np.array([100,60,90])

In [16]:
np.linalg.inv(X)@y

array([  0.8,   2.8, -34. ])

In [17]:
0.8*150+2.8*5+-34*1

100.0

In [18]:
0.8*200+2.8*10+-34

154.0